#!/usr/bin/env python3
"""
Fail-closed fairness and equity gate for publication-grade medical prediction.

Validates that subgroup fairness metrics meet thresholds required by top-tier
journals (Nature Medicine, Lancet Digital Health, JAMA, BMJ). Checks:
- Equalized odds gap across demographic/clinical subgroups
- Disparate impact ratio (80% rule)
- Subgroup-level metric minimums
- Coverage of subgroup analysis

References:
- TRIPOD+AI (BMJ 2024): fairness assessment recommendation
- PROBAST+AI (BMJ 2025): applicability across subpopulations
- Nature Medicine / Lancet DH: subgroup equity requirements
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Any, Dict, List, Optional

from _gate_utils import add_issue, load_json_from_str as load_json_object
from _gate_framework import (
    build_report_envelope,
    print_gate_summary,
    register_remediations,
)


register_remediations({
    "missing_evaluation_report": (
        "Provide --evaluation-report pointing to a valid evaluation_report.json "
        "generated by train_select_evaluate.py."
    ),
    "invalid_evaluation_report": (
        "Fix JSON syntax in evaluation_report.json. Use a JSON linter."
    ),
    "missing_subgroup_performance": (
        "evaluation_report.json must include 'subgroup_performance' section. "
        "Re-run training with sufficient binary/categorical features for subgroup analysis."
    ),
    "no_subgroups_analyzed": (
        "No subgroup columns were analyzed. Ensure dataset contains at least one "
        "binary or low-cardinality categorical feature for equity assessment."
    ),
    "equalized_odds_gap_exceeds_threshold": (
        "Sensitivity gap across subgroups exceeds threshold. Consider: "
        "1) Rebalancing training data across subgroups, "
        "2) Subgroup-aware threshold calibration, "
        "3) Fairness-constrained optimization."
    ),
    "disparate_impact_below_threshold": (
        "Disparate impact ratio < 0.8 (four-fifths rule). Consider: "
        "1) Investigating root cause of prediction disparity, "
        "2) Applying fairness-aware preprocessing (reweighting/resampling), "
        "3) Post-processing threshold adjustment per subgroup."
    ),
    "subgroup_metric_below_minimum": (
        "A subgroup has unacceptably low performance. Investigate: "
        "1) Sample size in that subgroup, "
        "2) Feature distribution differences, "
        "3) Whether the subgroup was adequately represented in training."
    ),
    "subgroup_sample_too_small": (
        "A subgroup has too few samples for reliable fairness assessment. "
        "Consider merging with related groups or flagging as underpowered."
    ),
    "fairness_not_finite": (
        "Non-finite fairness metric detected. Check evaluation code for "
        "division-by-zero in subgroup computations."
    ),
})


# ---------------------------------------------------------------------------
# Default thresholds
# ---------------------------------------------------------------------------
DEFAULT_THRESHOLDS: Dict[str, float] = {
    # Equalized odds: max sensitivity gap across subgroups
    "equalized_odds_gap_warn": 0.10,
    "equalized_odds_gap_fail": 0.15,
    # Disparate impact ratio (four-fifths / 80% rule)
    "disparate_impact_ratio_warn": 0.85,
    "disparate_impact_ratio_fail": 0.80,
    # Minimum PR-AUC for any subgroup
    "subgroup_pr_auc_min_warn": 0.50,
    "subgroup_pr_auc_min_fail": 0.40,
    # Minimum subgroup size for reliable assessment
    "min_subgroup_size": 20,
    # Minimum number of subgroup features analyzed
    "min_subgroups_analyzed": 1,
}


def _to_float(v: Any) -> Optional[float]:
    """Convert to float, reject non-finite."""
    if v is None:
        return None
    try:
        f = float(v)
        if not math.isfinite(f):
            return None
        return f
    except (TypeError, ValueError):
        return None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate subgroup fairness and equity metrics."
    )
    parser.add_argument(
        "--evaluation-report",
        required=True,
        help="Path to evaluation_report.json.",
    )
    parser.add_argument(
        "--report",
        help="Optional output JSON report path.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail on warnings.",
    )
    # Threshold overrides
    parser.add_argument(
        "--equalized-odds-gap-fail",
        type=float,
        default=None,
        help="Override equalized odds gap fail threshold.",
    )
    parser.add_argument(
        "--disparate-impact-ratio-fail",
        type=float,
        default=None,
        help="Override disparate impact ratio fail threshold.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    failures: List[Dict[str, Any]] = []
    warnings: List[Dict[str, Any]] = []
    info: List[Dict[str, Any]] = []

    thresholds = dict(DEFAULT_THRESHOLDS)
    if args.equalized_odds_gap_fail is not None:
        thresholds["equalized_odds_gap_fail"] = args.equalized_odds_gap_fail
    if args.disparate_impact_ratio_fail is not None:
        thresholds["disparate_impact_ratio_fail"] = args.disparate_impact_ratio_fail

    # Load evaluation report
    eval_path = Path(args.evaluation_report)
    if not eval_path.is_file():
        add_issue(
            failures,
            "missing_evaluation_report",
            f"Evaluation report not found: {eval_path}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    try:
        eval_report = load_json_object(eval_path.read_text(encoding="utf-8"))
    except Exception as exc:
        add_issue(
            failures,
            "invalid_evaluation_report",
            f"Cannot parse evaluation report: {exc}",
            {"path": str(eval_path)},
        )
        return _finish(args, failures, warnings, info, thresholds, None)

    # Extract subgroup performance
    subgroup_perf = eval_report.get("subgroup_performance")
    if not subgroup_perf:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "No subgroup_performance section in evaluation report.",
            {},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    # Validate subgroup data
    features_analyzed: List[str] = []
    all_equalized_odds_gaps: List[float] = []
    all_disparate_impact_ratios: List[float] = []
    all_subgroup_pr_aucs: List[Dict[str, Any]] = []
    subgroup_details: List[Dict[str, Any]] = []

    if isinstance(subgroup_perf, dict):
        items = subgroup_perf.items()
    elif isinstance(subgroup_perf, list):
        items = [(entry.get("feature", f"feature_{i}"), entry) for i, entry in enumerate(subgroup_perf)]
    else:
        add_issue(
            failures,
            "missing_subgroup_performance",
            "subgroup_performance has unexpected type.",
            {"type": type(subgroup_perf).__name__},
        )
        return _finish(args, failures, warnings, info, thresholds, eval_report)

    for feature_name, feature_data in items:
        if not isinstance(feature_data, dict):
            continue
        features_analyzed.append(str(feature_name))

        # Extract equalized odds gap
        eo_gap = _to_float(feature_data.get("equalized_odds_gap"))
        if eo_gap is not None:
            all_equalized_odds_gaps.append(eo_gap)

            if eo_gap > thresholds["equalized_odds_gap_fail"]:
                add_issue(
                    failures,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(fail threshold: {thresholds['equalized_odds_gap_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_fail"],
                    },
                )
            elif eo_gap > thresholds["equalized_odds_gap_warn"]:
                add_issue(
                    warnings,
                    "equalized_odds_gap_exceeds_threshold",
                    f"Equalized odds gap for '{feature_name}' is {eo_gap:.3f} "
                    f"(warn threshold: {thresholds['equalized_odds_gap_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "gap": eo_gap,
                        "threshold": thresholds["equalized_odds_gap_warn"],
                    },
                )

        # Extract disparate impact ratio
        di_ratio = _to_float(feature_data.get("disparate_impact_ratio"))
        if di_ratio is not None:
            all_disparate_impact_ratios.append(di_ratio)

            if di_ratio < thresholds["disparate_impact_ratio_fail"]:
                add_issue(
                    failures,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(fail threshold: {thresholds['disparate_impact_ratio_fail']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_fail"],
                    },
                )
            elif di_ratio < thresholds["disparate_impact_ratio_warn"]:
                add_issue(
                    warnings,
                    "disparate_impact_below_threshold",
                    f"Disparate impact ratio for '{feature_name}' is {di_ratio:.3f} "
                    f"(warn threshold: {thresholds['disparate_impact_ratio_warn']:.3f}).",
                    {
                        "feature": feature_name,
                        "ratio": di_ratio,
                        "threshold": thresholds["disparate_impact_ratio_warn"],
                    },
                )

        # Check subgroup-level metrics
        groups = feature_data.get("groups") or feature_data.get("subgroups") or []
        if isinstance(groups, dict):
            groups = [
                {**v, "group_label": k} if isinstance(v, dict) else {"group_label": k}
                for k, v in groups.items()
            ]
        for group in groups:
            if not isinstance(group, dict):
                continue
            n = group.get("n", group.get("count", 0))
            if isinstance(n, (int, float)) and n < thresholds["min_subgroup_size"]:
                add_issue(
                    warnings,
                    "subgroup_sample_too_small",
                    f"Subgroup '{group.get('group_label', '?')}' in feature "
                    f"'{feature_name}' has only {n} samples.",
                    {
                        "feature": feature_name,
                        "group": group.get("group_label"),
                        "n": n,
                        "min_required": thresholds["min_subgroup_size"],
                    },
                )
            pr_auc = _to_float(group.get("pr_auc"))
            if pr_auc is not None:
                all_subgroup_pr_aucs.append({
                    "feature": feature_name,
                    "group": group.get("group_label"),
                    "pr_auc": pr_auc,
                })
                if pr_auc < thresholds["subgroup_pr_auc_min_fail"]:
                    add_issue(
                        failures,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(fail: {thresholds['subgroup_pr_auc_min_fail']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )
                elif pr_auc < thresholds["subgroup_pr_auc_min_warn"]:
                    add_issue(
                        warnings,
                        "subgroup_metric_below_minimum",
                        f"PR-AUC for group '{group.get('group_label', '?')}' "
                        f"in '{feature_name}' is {pr_auc:.3f} "
                        f"(warn: {thresholds['subgroup_pr_auc_min_warn']:.3f}).",
                        {
                            "feature": feature_name,
                            "group": group.get("group_label"),
                            "pr_auc": pr_auc,
                        },
                    )

        subgroup_details.append({
            "feature": feature_name,
            "equalized_odds_gap": eo_gap,
            "disparate_impact_ratio": di_ratio,
            "n_groups": len(groups),
        })

    # Check minimum subgroup coverage
    if len(features_analyzed) < thresholds["min_subgroups_analyzed"]:
        add_issue(
            failures,
            "no_subgroups_analyzed",
            f"Only {len(features_analyzed)} subgroup feature(s) analyzed "
            f"(minimum: {int(thresholds['min_subgroups_analyzed'])}).",
            {"count": len(features_analyzed)},
        )

    # Summary
    summary = {
        "features_analyzed": features_analyzed,
        "n_features_analyzed": len(features_analyzed),
        "equalized_odds_gaps": all_equalized_odds_gaps,
        "max_equalized_odds_gap": (
            max(all_equalized_odds_gaps) if all_equalized_odds_gaps else None
        ),
        "disparate_impact_ratios": all_disparate_impact_ratios,
        "min_disparate_impact_ratio": (
            min(all_disparate_impact_ratios)
            if all_disparate_impact_ratios
            else None
        ),
        "subgroup_details": subgroup_details,
        "thresholds": thresholds,
    }

    return _finish(args, failures, warnings, info, thresholds, eval_report, summary)


def _finish(
    args: argparse.Namespace,
    failures: List[Dict[str, Any]],
    warnings: List[Dict[str, Any]],
    info: List[Dict[str, Any]],
    thresholds: Dict[str, float],
    eval_report: Optional[Dict[str, Any]],
    summary: Optional[Dict[str, Any]] = None,
) -> int:
    should_fail = bool(failures) or (args.strict and bool(warnings))
    status = "fail" if should_fail else "pass"

    report = build_report_envelope(
        gate_name="fairness_equity_gate",
        status=status,
        failures=failures,
        warnings=warnings,
        info=info,
        extra={
            "thresholds": thresholds,
            "summary": summary or {},
        },
    )

    if args.report:
        out = Path(args.report)
        out.parent.mkdir(parents=True, exist_ok=True)
        import json
        out.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    print_gate_summary("Fairness & Equity Gate", status, failures, warnings)
    return 2 if should_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
